// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    cold_weather_velocity_trend: {
        name: "cold_weather_velocity_trend";
        parameters: Record<string, never>;
        result: Array<Record<string, unknown>>;
      };
    worst_shortfalls: {
        name: "worst_shortfalls";
        parameters: Record<string, never>;
        result: Array<Record<string, unknown>>;
      };
    position_mix_by_zone: {
        name: "position_mix_by_zone";
        parameters: Record<string, never>;
        result: Array<Record<string, unknown>>;
      };
    governance_summary: {
        name: "governance_summary";
        parameters: Record<string, never>;
        result: Array<Record<string, unknown>>;
      };
  }
}
